version: "2"

linters:
  enable:
    - copyloopvar
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - nilerr
    - bodyclose
    - errorlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
